import {
  IsUUID,
  IsDateString,
  IsNumber,
  ValidateNested,
  IsArray,
} from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';

export class SyncOrderLineDto {
  @ApiProperty({
    example: '0192a7e0-1234-7abc-8def-0123456789ab',
    description: 'Product UUID',
  })
  @IsUUID()
  productId: string;

  @ApiProperty({ example: 2, description: 'Quantity sold' })
  @IsNumber()
  quantity: number;

  @ApiProperty({ example: 99.99, description: 'Unit price at sale' })
  @IsNumber()
  unitPrice: number;

  @ApiProperty({ example: 0, description: 'Discount rate (percentage)' })
  @IsNumber()
  discountRate: number;
}

export class SyncOrderDto {
  @ApiProperty({
    example: '0192a7e0-1234-7abc-8def-0123456789ab',
    description:
      'Client-generated UUID v7. MUST be generated by the device before sending.',
  })
  @IsUUID()
  id: string;

  @ApiProperty({
    example: '0192a7e0-1234-7abc-8def-0123456789ab',
    description: 'Customer/Partner UUID',
  })
  @IsUUID()
  partnerId: string;

  @ApiProperty({
    example: '2024-01-15T10:30:00Z',
    description: 'Order date and time (ISO 8601)',
  })
  @IsDateString()
  orderDate: string;

  @ApiProperty({ type: [SyncOrderLineDto], description: 'Order line items' })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SyncOrderLineDto)
  lines: SyncOrderLineDto[];
}
